name: aef_grits
channels:
  - conda-forge
dependencies:
  - python=3.12
  - affine
  - dask
  - earthengine-api
  - gdal
  - geopandas
  - mgrs
  - numpy
  - pandas
  - pyarrow
  - pyproj
  - pytest
  - rasterio
  - requests
  - scikit-learn
  - shapely>=2
  - xarray
  - zarr>=3.1
  - pip
  - pip:
      - -e .
